version: "3.9"
services:
  mongo_db:
    container_name: template
    image: mongo:latest
    restart: always
    ports:
      - "2717:27017"
    volumes:
      - mongo_db:/data/db
    networks:
      - templateserver

  template_redis:
    container_name: template-redis
    image: 'redis:alpine'
    restart: always
    ports:
      - "6379:6379"
    networks:
      - templateserver

  api:
    build: .
    image: {{your_username}}/template
    restart: always
    hostname: templateserver
    volumes:
      - .:/usr/src/app
    ports:
      - "${PORT}:${PORT}"
    networks:
      - templateserver
    environment:
      JWT_SECRET: "${JWT_SECRET}"
      PORT: "${PORT}"
      MONGODB_URI: "${MONGODB_URI}"
      MONGODB_URI_DEV: "${MONGODB_URI_DEV}"
      MAILER_SECURE: "${MAILER_SECURE}"
      MAILER_HOST: "${MAILER_HOST}"
      MAILER_PORT: "${MAILER_PORT}"
      MAILER_USER: "${MAILER_USER}"
      MAILER_PASSWORD: "${MAILER_PASSWORD}"
      CLOUDINARY_NAME: "${CLOUDINARY_NAME}"
      CLOUDINARY_APIKEY: "${CLOUDINARY_APIKEY}"
      CLOUDINARY_SECRET: "${CLOUDINARY_SECRET}"
      DOCKER: "true"
      BCRYPT_SALT: "${BCRYPT_SALT}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_HOST_DEV: "${REDIS_HOST_DEV}"
    depends_on:
      - mongo_db
      - template_redis

  nginx:
    build:
      context: ./nginx
    container_name: template-nginx
    environment:
      NGINX_HTTPS_PORT: "${NGINX_HTTPS_PORT}"
    hostname: nginx
    ports:
      - "${NGINX_HTTPS_PORT}:443"

    depends_on:
      - api
    networks:
      - templateserver
    volumes:
      - ./nginx/default.conf:/etc/nginxx/conf.d/default.conf

volumes:
  mongo_db: {}

networks:
  templateserver:
    external: true
